.Dd March 5th, 2023
.Dt scirc 1
.Os
.
.Sh NAME
.Nm scirc
.Nd pipe-friendly irc client
.
.Sh SYNOPSIS
.Nm
.Op Fl h Ar host
.Op Fl p Ar port
.Op Fl n Ar nick
.Op Fl u Ar username
.Op Fl r Ar realname
.Op Fl a Ar caps
.Op Fl s Ar sasltoken
.Op Fl j Ar channel
.Op Fl k Ar password
.Op Fl b Ar prefix
.Op Fl P
.Op Fl w
.Op Fl q
.Op Fl S
.
.Nm
.Op Fl v
.
.Sh DESCRIPTION
connect to an irc server

the arguments are as follows:
.
.Bl -tag -width Ds
.
.It Fl h Ar host
the
.Ar host
to connect to
.
.It Fl p Ar port
the
.Ar port
to connect to
.
.It Fl n Ar nick
set the nickname. uses value of the
.Ev USER
environment variable by default
.
.It Fl u Ar username
set the username/ident. uses value of
.Fl n Ar nickname
by default
.
.It Fl r Ar realname
set the realname. uses value of
.Fl n Ar nickname
by default
.
.It Fl a Ar caps
blindly request ircv3
.Ar caps .
each cap should be seperated by spaces,
which may require quotes when being invoked
by a shell.
.
.It Fl s Ar sasltoken
authenticate using sasl with base64-encoded
.Ar sasltoken .
requires
.Ql sasl
to be specified in
.Fl a Ar caps
to be useful

if
.Ar sasltoken
is set to an empty string, the value will be read from the
.Ev SCIRC_SASL
environment variable
.
.It Fl j Ar channel
join
.Ar channel
on connect
.
.It Fl k Ar password
specify
.Ar password
to send when connecting.
for authenticating with irc services such as
.Em NickServ ,
.Fl s
sasl should be preferred.

if
.Ar password
is set to an empty string, the value will be read from the
.Ev SCIRC_PASS
environment variable
.
.It Fl b Ar prefix
enable mode for making rudimentary pipe-based irc bots,
which redirects all normal messages to
.Pa stderr
and sends messages beginning with
.Ar prefix
to
.Pa stdout
with the
.Ar prefix
ommited
.
.It Fl P
enter rudimentary s2s mode for bad ircds.

this disables normal handshake, sources lines with
.Fl n Ar nick ,
and sends a
.Ql SERVER
line with
.Fl n Ar nick
as the name and
.Fl r Ar realname
as the description.

.Dl "PRIVMSG #channel :"
will no longer be included in front of bare lines.
additionally sources
.Ql PONG
lines with
.Fl n Ar nick .

this option may break or silently ignore other options,
including
.Fl w ,
.Fl j ,
and
.Fl S
.
.It Fl w
wait until after joining a channel before accepting any
input. useful for pipes, however you may become stuck during
a failed registration
.
.It Fl q
do not echo messages as they are sent
.
.It Fl S
automatically switch to a channel when receiving a message from it. if
.Fl b Ar prefix
is enabled, then switching will only happen when the message matches
.Ar prefix
.
.It Fl v
print the version and exit
.
.El
.
.Sh BUGS
please report any bugs found to
.Lk https://github.com/xfnw/scirc/issues
.
.Sh AUTHORS
.An xfnw Aq Mt xfnw@riseup.net
